services:
  # Сам веб-сервер
  httpd:
    image: "httpd:2.4.62"
    ports:
      - "8080:80"
    volumes:
      - "./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./static:/var/www"
    networks:
      backend:
        ipv4_address: 172.18.0.6
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/24"  # Явное определение подсети